# Generated by Django 3.2.8 on 2021-12-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='name')),
                ('number', models.CharField(max_length=250, verbose_name='number')),
            ],
            options={
                'verbose_name': 'buyer',
                'verbose_name_plural': 'buyers',
            },
        ),
    ]
